### ISSUE TITLE
Friet or patat?

### ISSUE THREAD

**Issue by FyorDev** [team-zomsa/aplib.net-demo#62]
Read the title ^

**Comment by QuakeEye** [comment]
![image](https://github.com/team-zomsa/aplib.net-demo/assets/74355598/6f017829-c8d6-4356-bace-732be938a4c8)

**Comment by SilasPeters** [comment]
Nondeju, das toch friet nie

**Comment by SilasPeters** [comment]
@FyorDev does this resolve your issue?

**Comment by QuakeEye** [comment]
> Nondeju, das toch friet nie

zuiderling gevonden

**Comment by FyorDev** [comment]
a

**Comment by QuakeEye** [comment]
opnieuw geopend want ik heb een frituurpan gevonden

**Comment by SilasPeters** [comment]
Wat voor frituurpan is het @QuakeEye ?

**Comment by FyorDev** [comment]
Zit er een krab in en heeft de krab het over Rustlang @QuakeEye ?

**Comment by nickname2002** [comment]
kibbeling = 🐐

**Comment by QuakeEye** [comment]
> Wat voor frituurpan is het @QuakeEye ?

zo eentje met vet

**Comment by QuakeEye** [comment]
> kibbeling = 🐐

maar welke saus neem jij daar bij?

**Comment by SilasPeters** [comment]
Cocktail saus

**Comment by QuakeEye** [comment]
> Cocktail saus

![Screenshot_20240506_112212_Google.jpg](https://github.com/team-zomsa/aplib.net-demo/assets/74355598/497f1b55-c117-4bc0-90ad-953c00ee7777)

**Comment by LuukBerkers** [comment]
Honingringen?

**Comment by QuakeEye** [comment]
> Honingringen?

Honingringen is gewoon de nederlandse vertaling van onion rings, dit kan gewoon in de frituur 💯

**Comment by SilasPeters** [comment]
En groningringen?

**Comment by QuakeEye** [comment]
> En groningringen?

![image](https://github.com/team-zomsa/aplib.net-demo/assets/74355598/b83cc862-7132-41b5-b7b7-66675cad541d)

**Comment by QuakeEye** [comment]
Nee maar for real, het is EN niet patat EN niet friet, het komt van patates frites, wat gefrituurde aardappel betekent.
Dus als je zegt dat je patat wilt, wil je alleen een aardappel, en als je zegt dat je friet wil, zeg je alleen dat je frituur/gefrituurd wilt. Hierom stel ik het nieuwe woord frietat voor, dat beter de originele taal en de daadwerkelijke betekenis capturet..... of pafriet... hmmmm.. of nog wat anders...

**Comment by SilasPeters** [comment]
Zowaar als dat ik onder de review geboren ben, is het friet en GEEN patat.

**Comment by nickname2002** [comment]
> Cocktail saus

Remove 'tail' and I can produce for you

**Comment by nickname2002** [comment]
> > kibbeling = 🐐
> 
> maar welke saus neem jij daar bij?

Stroop

**Comment by QuakeEye** [comment]
> Zowaar als dat ik onder de review geboren ben, is het friet en GEEN patat.

onder de review?

**Comment by QuakeEye** [comment]
> > Cocktail saus
> 
> Remove 'tail' and I can produce for you

![image](https://github.com/team-zomsa/aplib.net-demo/assets/74355598/82ee1795-ca79-470e-ade2-67368220a054)

**Comment by SilasPeters** [comment]
> > Cocktail saus
> 
> Remove 'tail' and I can produce for you

My USB port is always open for you, qt

**Comment by QuakeEye** [comment]
Closing issue as the frying pan has been lost, meaning the discussion is over, and our client wants to take a look at the repository, good luck everyone with your software projects!
